# Generated by Django 5.0.3 on 2024-04-01 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_usercategory_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_line', models.TextField()),
                ('tags', models.JSONField(default=list)),
                ('rating', models.FloatField()),
                ('likes', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
            ],
        ),
    ]
