# Generated by Django 5.0.3 on 2024-04-01 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_pickupline_likes_remove_pickupline_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
