# Generated by Django 5.0.3 on 2024-04-02 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_rating_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='pickup_line',
            new_name='pickup_line_id',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='user',
            new_name='user_id',
        ),
    ]
