# Generated by Django 5.0.3 on 2024-04-02 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_pickup_line_rating_pickup_line_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='pickup_line_id',
            new_name='pickup_line',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='user_id',
            new_name='user',
        ),
    ]
