# Generated by Django 5.0.3 on 2024-04-05 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_pickup_line_pickupline_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pickupline',
            old_name='text',
            new_name='pickup_line',
        ),
    ]
