# Generated by Django 5.0.3 on 2024-04-11 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_text_pickupline_pickup_line'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='created_at',
        ),
    ]
