# Generated by Django 5.0.3 on 2024-04-21 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_rating_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='pickup_line',
            new_name='pickup_line_id',
        ),
    ]
