# Generated by Django 5.0.3 on 2024-04-23 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_userprofile_delete_usercategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='preference_set',
            new_name='preferences_set',
        ),
    ]
